In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
df = pd.read_csv('customer.csv')

In [34]:
df.head(5)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [35]:
df = df.iloc[:,2:]

In [37]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [100]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [101]:
X_train

review education
28     Poor    School
27     Poor        PG
15     Poor        UG
29  Average        UG
48     Good        UG
45     Poor        PG
36     Good        UG
22     Poor        PG
42     Good        PG
35     Poor    School
18     Good    School
41     Good        PG
34  Average    School
39     Poor        PG
21  Average        PG
46     Poor        PG
19     Poor        PG
5   Average    School
31     Poor    School
10     Good        UG
25     Good    School
12     Poor    School
9      Good        UG
20  Average    School
26     Poor        PG
24  Average        PG
23     Good    School
4   Average        UG
3      Good        PG
11     Good        UG
0   Average    School
33     Good        PG
40     Good    School
2      Good        PG
6      Good    School
13  Average    School
7      Poor    School
17     Poor        UG
32  Average        UG
47     Good        PG

In [102]:
from sklearn.preprocessing import OrdinalEncoder

In [103]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [104]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [105]:
X_train = oe.transform(X_train)

In [106]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.]])

In [107]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [108]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.]])

In [109]:
from sklearn.preprocessing import LabelEncoder

In [110]:
le = LabelEncoder()

In [111]:
le.fit(y_train)

LabelEncoder()

In [112]:
y_train = le.transform(y_train)

In [113]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1])

In [ ]:
# Ordinal Encoder used for input categorical values
# Label Encoder used for output categorical values